version: '3.7'

services:
  database_provider:
    image: postgres
    container_name: database_provider
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=providers
      - POSTGRES_PASSWORD=prisma
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
